$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - node_modules
  - pnpm-lock.yaml
  - .tsbuildinfo
  - .gitignore
  - .github
  - .next
  - prisma
  - "**/*.svg"
  - .vscode/extensions.json
  - public
  - tsconfig.tsbuildinfo
words:
  - cmdk
  - commitlint
  - embla
  - frimousse
  - messageformat
  - nerdspace
  - onborda
  - sonner
  - vaul
